apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ms-ventas
  namespace: innova
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-ventas
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ms-despachos
  namespace: innova
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-despachos
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend
  namespace: innova
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: innova-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70